const VIBES=[{id:"warm",label:"Warm & Spicy"},{id:"romantic",label:"Floral & Soft"},{id:"slow",label:"Fresh & Clean"},{id:"adventure",label:"Woody & Deep"},{id:"elevated",label:"Oriental & Rich"}];
function firstName(){const e=(state.email||"").split("@")[0].replace(/[^a-zA-Z].*/,"")||"there";return e.charAt(0).toUpperCase()+e.slice(1)}
function partOfDay(){const h=new Date().getHours();return h<12?"morning":h<17?"afternoon":"evening"}
function weatherLine(){const w=state.weather;if(w==="hot")return "It's humid and sunny. Try something fresh.";if(w==="cold")return "It's cold out. Reach for something rich.";if(w==="cool")return "Cool air today. Something woody will sit well.";return "Mild day. A balanced layer will do."}
function matchPct(p){const s=typeof weatherFitScore==="function"?weatherFitScore(p,state.weather):8;return Math.max(18,Math.min(96,40+s*6))}
function notesShort(p){const n=[...(p.top||[]),...(p.heart||[])].slice(0,2);return n.length?n.join(" & "):(p.family||"—")}
function journeyCard(p,when){const pct=matchPct(p);return `<div class="journey" onclick="openDetail('${p.id}')"><div class="journey-thumb">${(p.name||"?")[0]}</div><div class="journey-body"><h4>${p.name}</h4><div class="journey-meta">${when} · ${state.weather} · ${notesShort(p)}</div><div class="bar"><i style="width:${pct}%"></i></div><div class="match">${pct}% match</div></div></div>`}
function renderVibes(){const row=document.getElementById("vibe-row");if(!row)return;row.innerHTML=VIBES.map(v=>`<button class="vibe ${state.mood===v.id?"on":""}" onclick="setMood('${v.id}')">${v.label}</button>`).join("")}
function setMood(id){state.mood=state.mood===id?null:id;renderHome()}
function filterMood(q){state.moodQuery=(q||"").toLowerCase()}
function renderHome(){const n=new Date();const clock=document.getElementById("clock");if(clock)clock.textContent=String(n.getHours()).padStart(2,"0")+":"+String(n.getMinutes()).padStart(2,"0");const greet=document.getElementById("home-greet");if(greet)greet.textContent=`Good ${partOfDay()}, ${firstName()}`;const wl=document.getElementById("weather-line");if(wl)wl.textContent=weatherLine();renderVibes();const layer=suggestLayer();const cards=document.getElementById("layer-cards");if(!cards)return;if(!layer||layer.reason==="none"||!layer.primary){cards.innerHTML=`<div class="glass" style="padding:16px"><p class="muted">${state.owned.size===0?"Add bottles in My Collection to get a layer.":"None of your bottles fit this weather."}</p></div>`;return}if(!layer.support){cards.innerHTML=journeyCard(layer.primary,partOfDay()==="evening"?"Evening Layer":"Morning Layer");return}cards.innerHTML=journeyCard(layer.primary,"Morning Layer")+journeyCard(layer.support,"Evening Layer")}
if(document.getElementById("page-home")) renderHome();
